name: CI
on: 
  workflow_dispatch:
 

jobs:
 check01:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - uses: actions/checkout@v2
        name: Checkout
      - name: Run Checking
        run: |
            curl ipinfo.io
            sleep 5
        shell: bash
